# Note that only one of these targets is required

bigquery-dw:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dw-stalse-01
      dataset: airbyte # You can also use "schema" here
      threads: 1

      # optional
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false