bigquery-dw:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dw-stalse-01
      dataset: airbyte # You can also use "schema" here
      threads: 1

      # optional
      connect_retries: 3
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False
      job_execution_timeout_seconds: 1200 # 20 minutes