version: 2

sources:
  - name: raw_table
    schema: hubspot_ftb
    database: dw-stalse-01
    description: raw data of table.
    tables:
      - name: _airbyte_raw_companies
        columns:
          - name: _airbyte_data
            description: description airbyte_data.
            tests:
              - unique
              - not_null

      - name: _airbyte_raw_contacts
        columns:
          - name: _airbyte_data
            description: description airbyte_data.
            tests:
              - unique
              - not_null


models:
  - name: base_companies
    config:
      materialized: view

  - name: base_contacts
    config:
      materialized: view 